### ISSUE TITLE
ComponentBuilder does not set AltText

### ISSUE THREAD

**Issue by jarnohenneman** [dd4t/dynamic-delivery-4-tridion#1]
When requesting the multimedia.AltText it always returns null. When looking in the ComponentBuilder.cs it is not filled. My assumption was that we could create our own multimedia schema and add an "AltText" field that would be filled automaticly. Can someone tell me what the use of this field is, and if this assumption is correct ? If so the following change is suggested;

ComponentBuilder.cs
Line_43: multimedia.AltText = tcmComponent.Content["AltText"].Value;

**Comment by quirijnslings** [comment]
I want to remove AltText from the multimedia altogether (see https://github.com/dd4t/DD4T.Model/issues/18). 
IMO AltText is part of the content, not of the multimedia. With viewmodels it is now easy to map an AltText property to any content or metadata field you like.
