### ISSUE TITLE
RenderComponentPresentationsByView should work without metadata field 'view'

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dynamic-delivery-4-tridion#16]
Currently this method does not work if your CTs are mapped to views through their title.

**Comment by mvbrakel** [comment]
Taking a look at this

**Comment by mvbrakel** [comment]
Can someone check if this bug is solved with the above merge? I made it myself so not a real good tester for this :smile:

**Comment by quirijnslings** [comment]
Sorry, forgot to comment back..
